
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_EPL2182_NEW),y)
obj-y	+=  EPL2182-new/
endif
ifeq ($(CONFIG_MTK_LTR559),y)
obj-y	+=  LTR559/
endif
ifeq ($(CONFIG_MTK_LTR559_NEW),y)
obj-y	+=  ltr559-new/
endif